// =====================================================================
// Taksonomi tipe insiden (satu sumber untuk Investigasi Sederhana & RCA,
// agar analisis tren per tipe konsisten). Kunci diawali nomor urut.
// =====================================================================
const TAKSONOMI_INSIDEN = {
            "1. ADMINISTRASI KLINIK": { "a. Proses": ["Serah terima", "Perjanjian", "Daftar tunggu / Antrian", "Rujukan / Konsultasi", "Admisi", "Keluar/Pulang dari Ranap/RS", "Pindah Perawatan (Transfer of care)", "Identifikasi Pasien", "Consent", "Pembagian tugas", "Respons terhadap kegawatdaruratan"], "b. Masalah": ["Tidak performed ketika dibutuhkan/indikasi", "Tidak lengkap / Inadekuat", "Tidak tersedia", "Salah pasien", "Salah proses / pelayanan"] },
            "2. PROSES / PROSEDUR KLINIS": { "a. Proses": ["Skrining / Pencegahan / Medical check up", "Diagnosis / Assessment", "Prosedur / Pengobatan / Intervensi", "General care / Management", "Test / Investigasi", "Spesimen / Hasil", "Belum dipulangkan (Detention/Restraint)"], "b. Masalah": ["Tidak performance ketika dibutuhkan/ indikasi", "Tidak lengkap / Inadekuat", "Tidak tersedia", "Salah pasien", "Salah proses / pengobatan / prosedur", "Salah bagian tubuh / sisi"] },
            "3. DOKUMENTASI": { "a. Dokumen Terkait": ["Order / Permintaan", "Chart / Rekam medik / Assessment/ Konsultasi", "Check list", "Form / sertifikat", "Instruksi / Informasi / Kebijakan / SPO /Guideline", "Label / Stiker / Identifikasi Bands / Kartu", "Surat / E-mail / Rekaman Komunikasi", "Laporan / Hasil / Images"], "b. Masalah": ["Dokumen hilang / tidak tersedia", "Terlambat mengakses dokumen", "Salah dokumen / Salah orang", "Tidak jelas / Membingungkan /Illegible"] },
            "4. INFEKSI NOSOKOMIAL (HAI)": { "a. Tipe organisme": ["Bakteri", "Virus", "Jamur", "Parasit", "Protozoa", "Rickettsia", "Prion (Partikel protein yang infeksius)", "Organisme tidak teridentifikasi"], "b. Tipe / Bagian infeksi": ["Bloodstream", "Bagian yang dioperasi", "Abses", "Pneumonia", "Kanul IV", "Protesis infeksi", "Drain/ tube urin", "Jaringan lunak"] },
            "5. MEDIKASI/ CAIRAN INFUS": { "a. Medikasi/Cairan terkait": ["Daftar Medikasi", "Daftar Cairan infus"], "b. Proses penggunaan": ["Peresepan", "Persiapan / Dispensing", "Pemaketan", "Pengantaran", "Pemberian", "Supply / pesan", "Penyimpanan", "Monitoring"], "c. Masalah": ["Salah pasien", "Salah obat", "Salah dosis / kekuatan / frekuensi", "Salah formulasi / presentasi", "Salah rute pemberian", "Salah jumlah / kuantitas", "Salah Dispensing Label / Instruksi", "Kontraindikasi", "Salah penyimpanan", "Ommited medicine or dose", "Obat kadaluarsa", "Adverse drug"] },
            "6. TRANSFUSI DARAH / PRODUK DARAH": { "a. Produk terkait": ["Produk selular", "Faktor pembekuan (clothing)", "Albumin / Plasma protein", "Imunoglobulin"], "b. Proses Transfusi": ["Tes pre transfusi", "Peresepan", "Persiapan / Dispensing", "Pengantaran", "Pemberian", "Penyimpanan", "Monitoring", "Presentasi / Pemaketan", "Suply / Pesan"], "c. Masalah": ["Salah pasien", "Salah Darah / Produk darah", "Salah dosis / Frekuensi", "Salah jumlah", "Salah label dispensing / Instruksi", "Kontraindikasi", "Salah penyimpanan", "Obat atau Dosis yang diabaikan", "Darah kadaluarsa", "Efek samping (Adverse effect)"] },
            "7. NUTRISI": { "a. Nutrisi terkait": ["Nutrisi umum", "Nutrisi khusus"], "b. Proses nutrisi": ["Peresepan / Permintaan", "Pesiapan / Manufaktur / memasak", "Supply / order", "Penyajian", "Dispensing / Alokasi", "Pengantaran", "Pemberian", "Penyimpanan"], "c. Masalah": ["Salah pasien", "Salah diet", "Salah jumlah", "Salah Frekuensi", "Salah konsistensi"] },
            "8. OKSIGEN / GAS": { "a. Oksigen / Gas terkait": ["Daftar oksigen /gas terkait"], "b. Proses penggunaan": ["Label silinder / warna kode / Index pin", "Peresepan", "Pemberian", "Pengantaran", "Suply / order"], "c. Masalah": ["Salah pasien", "Salah gas", "Salah rate / flow/ konsentrasi", "Salah mode pengantaran", "Kontraindikasi", "Salah penyimpanan", "Gagal pemberian", "Kontaminasi"] },
            "9. ALAT MEDIS / ALAT KESEHATAN": { "a. Tipe Alat / Equipment": ["Daftar Alat medis / Alat kesehatan / Equipment property"], "b. Masalah": ["Presentasi / Pemaketan tidak baik", "Ketidaktersediaan", "Inapropiate for task", "Tidak bersih / Tidak steril", "Kegagalan / Malfungsi"] },
            "10. PASIEN": { "a. Perilaku pasien": ["Tidak kooperatif", "Tidak pantas / Sikap bermusuhan / Kasar", "Berisiko/ Sembrono / Berbahaya", "Masalah dengan penggunaan substansi / Abuse", "Menggangu (Harrassment)", "Diskriminasitif / Berprasangka", "Berkeliaran, Melarikan diri.", "Sengaja mencederai diri, Bunuh diri."], "b. Agresi / Assault": ["Agresi verbal", "Kekerasan fisik", "Ancaman nyawa"] },
            "11. JATUH": { "a. Tipe Jatuh": ["Tersandung", "Slip", "Kolaps", "Hilang keseimbangan"], "b. Keterlibatan saat jatuh": ["Velbed", "Tempat tidur", "Kursi", "Strecher", "Toilet", "Peralatan terapi", "Tangga", "Dibawa/dibantu oleh orang lain"] },
            "12. KECELAKAAN": { "a. Benturan tumpul": ["Kontak dengan benda/binatang", "Kontak dengan orang", "Hancur, remuk"], "b. Serangan tajam/ tusukan": ["Cakaran", "Sayatan", "Tusukan", "Gigitan", "Sengatan"], "c. Kejadian mekanik lain": ["Benturan akibat ledakan bom", "Kontak dengan mesin"], "d. Mekanisme Panas": ["Panas yg berlebihan, dingin yg berlebihan"], "e. Ancaman pernafasan": ["Ancaman mekanik pernafasan, tenggelam atau hampir tenggelam, pembatasan oksigen - kekurangan tempat"], "g. Paparan bahan kimia": ["Keracunan bahan kimia atau substansi lain", "Bahan kimia korosif"], "h. Mekanisme spesifik lain": ["Paparan listrik/radiasi", "Paparan suara/ getaran"] },
            "13. INFRASTRUKTUR / BANGUNAN": { "a. Keterlibatan Struktur": ["Daftar struktur", "Daftar Bangunan", "Daftar Furniture"], "b. Masalah": ["Inadekuat", "Damaged/Faulty/Worn"] },
            "14. RESOURCE / MANAJEMEN ORGANISASI": { "a. Beban kerja manajemen": ["Ketersediaan/ keadekuatan tempat tidur/ pelayanan", "Sumber Daya Manusia", "Ketersediaan/ keadekuatan staf", "Organisasi/ Tim"], "b. Protocols/ SOP Guideline": ["Tidak Ada SOP", "SOP Inadekuat/Tidak Jelas", "SOP Tidak Dipatuhi"], "c. Ketersediaan / Adequacy": ["Inadekuat", "Tidak Tersedia"] },
            "15. LABORATORIUM / PATOLOGI": { "a. Proses Lab": ["Pengambilan/ Pick up", "Transport", "Sorting", "Data entry", "Prosesing", "Verifikasi / Validasi Hasil"] }
        };

// Cari kunci taksonomi dari teks tersimpan (juga data lama yang nomornya berbeda,
// mis. "5. JATUH" di RCA lama = "11. JATUH")
function cariKunciTaksonomi(teks) {
    if (!teks) return '';
    if (TAKSONOMI_INSIDEN[teks]) return teks;
    const nama = String(teks).replace(/^\s*\d+\.\s*/, '').trim().toLowerCase();
    return Object.keys(TAKSONOMI_INSIDEN).find(k => k.replace(/^\s*\d+\.\s*/, '').trim().toLowerCase() === nama) || '';
}
if (typeof module !== 'undefined') module.exports = { TAKSONOMI_INSIDEN, cariKunciTaksonomi };
